---
- name: Launch AWS EC2 Instance
  hosts: localhost
  gather_facts: no
  vars:
    instance_type: t2.micro
    key_name: aws-ec2-key-1
    region: ap-south-1
    image_id: ami-0c94855ba95c71c99 # Example Amazon Linux 2 AMI
    security_group_name: flask-demo-sg
  tasks:
    - name: Create security group for Flask demo
      community.aws.ec2_security_group:
        name: "{{ security_group_name }}"
        description: "Allow HTTP, HTTPS, and SSH access"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        var: ec2
